import type { Metadata } from 'next'
import { Lilita_One } from 'next/font/google'
import './globals.css'

const lilita = Lilita_One({
  subsets: ['latin'],
  variable: "--var-lilita",
  weight: '400',
});

export const metadata: Metadata = {
  title: 'MU',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lilita.variable}>{children}</body>
    </html>
  )
}
