import type { Metadata } from 'next'
import { Lilita_One, Inter } from 'next/font/google'
import './globals.css'

const lilita = Lilita_One({
  subsets: ['latin'],
  variable: "--var-lilita",
  weight: '400',
});

const inter = Inter({
  subsets: ['latin'],
  variable: "--var-inter",
})

export const metadata: Metadata = {
  title: 'MY',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={`${lilita.variable} ${inter.variable}`}>{children}</body>
    </html>
  )
}
